### ISSUE TITLE
panic: Use of unexported embedded struct

### ISSUE THREAD

**Issue by zirkome** [evalphobia/logrus_fluent#14]
<details>
<summary>Go Panic StackTrace</summary>

```
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x1138ce0, 0xc4200ba080, 0xd4, 0xc4200ac001, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.1/libexec/src/reflect/value.go:936 +0x1a5
reflect.Value.Interface(0x1138ce0, 0xc4200ba080, 0xd4, 0xa, 0x11fdc20)
	/usr/local/Cellar/go/1.8.1/libexec/src/reflect/value.go:925 +0x44
github.com/evalphobia/logrus_fluent.converFromStruct(0x1147100, 0xc4200ba080, 0x116003f, 0x6, 0xc4200ba080, 0x113e020)
	/Users/zirkome/.go/src/github.com/evalphobia/logrus_fluent/reflect.go:66 +0x3c2
github.com/evalphobia/logrus_fluent.ConvertToValue(0x113e020, 0xc4200ba060, 0x116003f, 0x6, 0xc4200ba060, 0x98)
	/Users/zirkome/.go/src/github.com/evalphobia/logrus_fluent/reflect.go:14 +0x127
github.com/evalphobia/logrus_fluent.convertFromMap(0x11390e0, 0xc4200b2150, 0x15, 0x116003f, 0x6, 0xc42004fc38, 0xc4200c0240)
	/Users/zirkome/.go/src/github.com/evalphobia/logrus_fluent/reflect.go:32 +0x219
github.com/evalphobia/logrus_fluent.ConvertToValue(0x11390e0, 0xc4200b2150, 0x116003f, 0x6, 0x122ac01, 0x1148700)
	/Users/zirkome/.go/src/github.com/evalphobia/logrus_fluent/reflect.go:16 +0x1b1
github.com/evalphobia/logrus_fluent.(*FluentHook).Fire(0xc4200ae050, 0xc4200ae140, 0x0, 0x0)
	/Users/zirkome/.go/src/github.com/evalphobia/logrus_fluent/fluent.go:148 +0x31a
github.com/Sirupsen/logrus.LevelHooks.Fire(0xc42007a180, 0xc4255b7b02, 0xc4200ae140, 0xd, 0xc42004fe10)
	/Users/zirkome/.go/src/github.com/Sirupsen/logrus/hooks.go:28 +0x8b
github.com/Sirupsen/logrus.Entry.log(0xc4200720f0, 0xc4200b2120, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4200ac002, ...)
	/Users/zirkome/.go/src/github.com/Sirupsen/logrus/entry.go:96 +0x109
github.com/Sirupsen/logrus.(*Entry).Error(0xc4200ae0f0, 0xc42004ff20, 0x1, 0x1)
	/Users/zirkome/.go/src/github.com/Sirupsen/logrus/entry.go:156 +0xaa
main.logging()
	/Users/zirkome/work/src/github.com/myorg/myrepo/main.go:25 +0xf3
main.main()
	/Users/zirkome/work/src/github.com/myorg/myrepo/main.go:20 +0xc2
exit status 2
```

</details>

The code to reproduce this is here: https://gist.github.com/kokaz/15438e811565815c6648a8723e877aee

The cause is related to `pkg/errors` using an anonymous embedded struct to store stack trace:

```go
type withStack struct {
    error
    *stack
}
```

This bug was introduced in https://github.com/evalphobia/logrus_fluent/pull/13.

The root cause IMO is due to the way reflection is done as `encoding/json` and `encoding/xml` does handle correctly the reflection in this case.

**Comment by zirkome** [comment]
Fixed by #15
